Cfg = {}
Cfg.Ranks = {
    ['vineyard'] = {
        depositRank = 2,
        withdrawRank = 6,
        groupTaskRank = 2,
        assignTaskRank = 4,
        hireRank = 5,
        fireRank = 5,
        promoteRank = 4,
    },
    ['mechanic1'] = {
        depositRank = 1,
        withdrawRank = 4,
        groupTaskRank = 2,
        assignTaskRank = 4,
        hireRank = 5,
        fireRank = 5,
        promoteRank = 4,
    },
    ['pdm'] = {
        depositRank = 2,
        withdrawRank = 4,
        groupTaskRank = 2,
        assignTaskRank = 4,
        hireRank = 5,
        fireRank = 5,
        promoteRank = 4,
    },
    ['police'] = {
        depositRank = 2,
        withdrawRank = 4,
        groupTaskRank = 2,
        assignTaskRank = 4,
        hireRank = 5,
        fireRank = 5,
        promoteRank = 4,
    },
    ['ambulance'] = {
        depositRank = 2,
        withdrawRank = 4,
        groupTaskRank = 2,
        assignTaskRank = 4,
        hireRank = 5,
        fireRank = 5,
        promoteRank = 4,
    },
    ['trucker'] = {
        depositRank = 2,
        withdrawRank = 4,
        groupTaskRank = 2,
        assignTaskRank = 4,
        hireRank = 5,
        fireRank = 5,
        promoteRank = 4,
    },
    ['realestate'] = {
        depositRank = 2,
        withdrawRank = 4,
        groupTaskRank = 2,
        assignTaskRank = 4,
        hireRank = 5,
        fireRank = 5,
        promoteRank = 4,
    },
    ['tow'] = {
        depositRank = 2,
        withdrawRank = 4,
        groupTaskRank = 2,
        assignTaskRank = 4,
        hireRank = 5,
        fireRank = 5,
        promoteRank = 4,
    },
    ['reporter'] = {
        depositRank = 2,
        withdrawRank = 4,
        groupTaskRank = 2,
        assignTaskRank = 4,
        hireRank = 5,
        fireRank = 5,
        promoteRank = 4,
    },
    ['lostmc'] = {
        depositRank = 2,
        withdrawRank = 4,
        groupTaskRank = 2,
        assignTaskRank = 4,
        hireRank = 5,
        fireRank = 5,
        promoteRank = 4,
    },
    ['judge'] = {
        depositRank = 2,
        withdrawRank = 4,
        groupTaskRank = 2,
        assignTaskRank = 4,
        hireRank = 5,
        fireRank = 5,
        promoteRank = 4,
    },
    ['lawyer'] = {
        depositRank = 2,
        withdrawRank = 4,
        groupTaskRank = 2,
        assignTaskRank = 4,
        hireRank = 5,
        fireRank = 5,
        promoteRank = 4,
    },
    ['cardealer'] = {
        depositRank = 2,
        withdrawRank = 4,
        groupTaskRank = 2,
        assignTaskRank = 4,
        hireRank = 5,
        fireRank = 5,
        promoteRank = 4,
    },
    ['mechanic'] = {
        depositRank = 2,
        withdrawRank = 4,
        groupTaskRank = 2,
        assignTaskRank = 4,
        hireRank = 5,
        fireRank = 5,
        promoteRank = 4,
    },
    ['pawnshop'] = {
        depositRank = 2,
        withdrawRank = 4,
        groupTaskRank = 2,
        assignTaskRank = 4,
        hireRank = 5,
        fireRank = 5,
        promoteRank = 4,
    },
    ['cartel'] = {
        depositRank = 2,
        withdrawRank = 4,
        groupTaskRank = 2,
        assignTaskRank = 4,
        hireRank = 5,
        fireRank = 5,
        promoteRank = 4,
    },
    ['mechanic3'] = {
        depositRank = 2,
        withdrawRank = 4,
        groupTaskRank = 2,
        assignTaskRank = 4,
        hireRank = 5,
        fireRank = 5,
        promoteRank = 4,
    },
    ['playboys'] = {
        depositRank = 2,
        withdrawRank = 4,
        groupTaskRank = 2,
        assignTaskRank = 4,
        hireRank = 5,
        fireRank = 5,
        promoteRank = 4,
    },
    ['rdaa'] = {
        depositRank = 2,
        withdrawRank = 4,
        groupTaskRank = 2,
        assignTaskRank = 4,
        hireRank = 5,
        fireRank = 5,
        promoteRank = 4,
    },
    ['yellowjack'] = {
        depositRank = 2,
        withdrawRank = 4,
        groupTaskRank = 2,
        assignTaskRank = 4,
        hireRank = 5,
        fireRank = 5,
        promoteRank = 4,
    },
    ['coral'] = {
        depositRank = 2,
        withdrawRank = 4,
        groupTaskRank = 2,
        assignTaskRank = 4,
        hireRank = 5,
        fireRank = 5,
        promoteRank = 4,
    },
    ['tequilala'] = {
        depositRank = 2,
        withdrawRank = 4,
        groupTaskRank = 2,
        assignTaskRank = 4,
        hireRank = 5,
        fireRank = 5,
        promoteRank = 4,
    },
    ['racecrew'] = {
        depositRank = 2,
        withdrawRank = 4,
        groupTaskRank = 2,
        assignTaskRank = 4,
        hireRank = 5,
        fireRank = 5,
        promoteRank = 4,
    },
}